### ISSUE TITLE
Agree on project vision

### ISSUE THREAD

**Issue by Mishkun** [Inkremental/anvil#2]
We need to have some additional value to make a fork. The most obvious one is androidX migration. Any further ideas a welcome

**Comment by sgrekov** [comment]
One of the most obvious reasons for is to rewrite core part and dsl in Kotlin. But before that we need to found out the benefits of moving to Kotlin.

**Comment by Mishkun** [comment]
The main benefits that I see are
- dropping the support of Java DSL (less work for us to do)
- better Kotlin support with DslMarkers, context-bound extension functions, nullable values and so on
- party tricks with infix and inline functions, reified generics

**Comment by dector** [comment]
Another one reason to use Kotlin is that Google claimed its libraries as Kotlin-first. Seems than native android development is moving towards this direction.

**Comment by dector** [comment]
So, draftly features list looks like this:

- [ ] AndroidX support (_is it already merged into original project?_).
- [ ] Kotlin-only library (no Java API support).
- [ ] `DslMarkers`, better nullability control, inline/infix functions.
- [ ] _(?)_ Serializable view hierarchies (e.g. for server-side UI). ~~Hello, Compose.~~
- [ ] _(?)_ Extend DSL to other UI frameworks (e.g. JavaFx) - can be useful as a research and/or fast prototyping approach.

cc: @Mishkun @sgrekov @r4zzz4k

**Comment by r4zzz4k** [comment]
My five cents:
> (is it already merged into original project?).

On one hand, it's already merged into ours. On the other hand, the way things go really depends on how we would coordinate our fork with the previous maintainer -- would this project be official continuation of Anvil or a usual fork.

> (?) Extend DSL to other UI frameworks (e.g. JavaFx)

I'd probably postpone discussion on other UI frameworks as there is a long way to go: @sgrekov has correctly noticed that DSL is tied to Android right now, so the first step would be to setup multiplatform project structure and start abstracting out and pulling parts of current API into common module.

**Comment by dector** [comment]
Yes, serializable view hierarchies and DSLs for other UI frameworks are definitely quite far from the current point. However, sometimes it's nice to keep such things in the head while making various decisions.

**Comment by sgrekov** [comment]
Another Kotlin feature that we can use is inline classes. We can use them instead of Int, where we are awaiting for specific Int, like dp, sp, ResInt, etc

**Comment by Mishkun** [comment]
Clearly, Issue is resolved. To sum up conversations held here and in other places, the main idea of making this project as a fork of Anvil is to provide easy-to-use Kotlin-based performant View-DSL.

Main points to use Inkremental vs Anvil:
- Kotlin-first
- (future) Multiplatform support

Main points to use Inkremental vs Jetpack Compose%
- Easy migration
- Flat learning curve
- Intermediate step before full Compose migration
