### ISSUE TITLE
Decide on CI

### ISSUE THREAD

**Issue by r4zzz4k** [Inkremental/anvil#29]
Right now we have both Circle CI (#1) and Travis set up. Travis config is up to date, CircleCI needs attention. We should decide which one we would use, configure it if needed and disable the other one.

**Comment by dector** [comment]
Github Actions :sweat_smile:

**Comment by r4zzz4k** [comment]
Seems that it's free for public repos, and can be configured via yamls and Dockerfiles. Thanks for clarifications in chat, @dector! We'll definitely take a thoughtful look when get to considerations on CI :)
