### ISSUE TITLE
Make new readme

### ISSUE THREAD

**Issue by Mishkun** [Inkremental/anvil#4]
When agreed on vision and made new CI pipelines, update projects readme with clear vision and credits to the base project.

**Comment by Mishkun** [comment]
I think that we need other name for this project to distinguish it from the original work. I suggest AnvilX, like in androidx. @sgrekov what do you think?

**Comment by sgrekov** [comment]
Hmm, not really sure about AndroidX.. If original Anvil will merge androidX PR then the difference will be very hard to distinguish.. Also this name has no hints about the main reasons of fork..
Honestly, name "Inkremental" seems a very good fit.

**Comment by dector** [comment]
+1 for "Inkremental".
