### ISSUE TITLE
Setup releases and snapshot Maven repositories

### ISSUE THREAD

**Issue by r4zzz4k** [Inkremental/anvil#52]
Right now we try to publish release version each time we push something to master. This fails when the version is already there, so we don't actually have artifacts for each merged PR.

Idea (found at https://gitlab.com/serebit/strife with @serebit kindly providing some clarifications, thank you!) is as follows:
1. Release Maven repository should be set up with manual publishing. We should have a manual switch to put new version in the wild. This may be further moderated with some ops solution, but let's leave this for #37.
2. Snapshots Maven repository should be used for automatic publishing on each master commit. As Bintray doesn't support snapshot versions (and to have ability to consume specific artifact anyway) we can append e.g. commit hash to version tag.

As this is prerequisite to proper release management, I'd say it should be done before 1.0. @sgrekov, @Mishkun, WDYT?

**Comment by sgrekov** [comment]
I think that for 1.0 we should have published binary artifacts with established versioning schema, but how 
we do them behind the scenes is not that important. If the can guarantee that current schema will hold for future improvements of publishing mechanism, then good to go!

**Comment by r4zzz4k** [comment]
On the other hand, we can update version for each PR with changes to functionality for the time being.
