### ISSUE TITLE
Better experience for preview

### ISSUE THREAD

**Issue by sgrekov** [Inkremental/anvil#62]
Currently, if you want to have working preview for Inkremental components, you need to put this component to layout xml file to emulate preview from AGP. Also, if one needs to be  updated in preview window, you need to rebuild project. You can also use technique to move renderable components to separate module in order to not rebuild the whole project, but only UI component which can speed up refreshing significantly for big projects. 
This issue is a place for all ideas and suggestions of how this experience can be improved (IJ plugin for example or other techniques)

**Comment by r4zzz4k** [comment]
Things to check out:
https://github.com/LouisCAD/Splitties/tree/master/modules/views-dsl-ide-preview
https://github.com/Kotlin/anko/tree/master/anko/idea-plugin/preview
