### ISSUE TITLE
ERROR: Failed to resolve: co.inkremental:anvil-sdk21:0.9

### ISSUE THREAD

**Issue by ugommirikwe** [Inkremental/anvil#67]
Hi,

So, I've tried for several hours to install your library with Gradle, but keep getting this error: "ERROR: Failed to resolve: co.inkremental:anvil-sdk21:0.9" 

To be sure I've added `maven { url "https://dl.bintray.com/inkremental/maven" }` in the `build.gradle` file too, so not sure where the issue is from.

cc. @sgrekov

**Comment by sgrekov** [comment]
Hi! 
Can you try this one? 

implementation "dev.inkremental:anvil-sdk:21-0.11"

**Comment by ugommirikwe** [comment]
> Hi!
> Can you try this one?
> 
> implementation "dev.inkremental:anvil-sdk:21-0.11"

@sgrekov
Nope, still the same error: `ERROR: Failed to resolve: dev.inkremental:anvil-sdk:21-0.11`

**Comment by sgrekov** [comment]
Do you have    maven { url "https://dl.bintray.com/inkremental/maven" } in repositories block, like here?

repositories {
        maven { url "https://dl.bintray.com/inkremental/maven" }
    }

**Comment by sgrekov** [comment]
@ugommirikwe 
You can compare your setup with how it is done in this project for example 
https://github.com/sgrekov/UdfDemo/blob/master/teapotwithinkremental/build.gradle

**Comment by ugommirikwe** [comment]
> Do you have maven { url "https://dl.bintray.com/inkremental/maven" } in repositories block, like here?
> 
> repositories {
> maven { url "https://dl.bintray.com/inkremental/maven" }
> }

@sgrekov 

Here's what my repositories block look like:
```
repositories {
     maven { url "https://maven.fabric.io/public" }
     google()
     jcenter()
     maven { url "https://dl.bintray.com/inkremental/maven" }
}
```

**Comment by ugommirikwe** [comment]
> @ugommirikwe
> You can compare your setup with how it is done in this project for example
> https://github.com/sgrekov/UdfDemo/blob/master/teapotwithinkremental/build.gradle

@sgrekov 

Should I move the maven url to the topmost level `build.gradle` file or just leave it in the specific module `build.gradle` file?

**Comment by ugommirikwe** [comment]
> > @ugommirikwe
> > You can compare your setup with how it is done in this project for example
> > https://github.com/sgrekov/UdfDemo/blob/master/teapotwithinkremental/build.gradle
> 
> @sgrekov
> 
> Should I move the maven url to the topmost level `build.gradle` file or just leave it in the specific module `build.gradle` file?

@sgrekov 

That was the issue: I moved the `maven { url "https://dl.bintray.com/inkremental/maven" }` to the topmost `build.gradle` file, in the `allProjects` section, like here: https://github.com/sgrekov/UdfDemo/blob/f61782e5e53f1fcc564e392cccaa13e75f4228ec/build.gradle#L18

Much thanks for your assistance. 👍
