### ISSUE TITLE
How do you use this with Fragment?

### ISSUE THREAD

**Issue by ugommirikwe** [Inkremental/anvil#68]
I've tried:
```
override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {

        val vi = requireActivity().renderableContentView {
            linearLayout {
                size(Size.MATCH, Size.MATCH)
                orientation(LinearLayout.VERTICAL)

                textView {
                    text("Basics")
                    onClick {
                        //startActivity(Intent(context, BasicsActivity::class.java))
                    }

                    size(Size.WRAP, Size.WRAP)
                    padding(16.dp)

                    paintFlags(Paint.UNDERLINE_TEXT_FLAG)
                    textColor(Color.BLUE)
                }
         }
    }

  return vi
}

```

but I always get the error: `java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

How does this really work?

cc. @sgrekov (Apologies that I tag you, if you have a Slack Channel, I'd gladly direct queries there.)

**Comment by sgrekov** [comment]
@ugommirikwe  We have channel in KotlinLang Slack, feel free to ask questions there.

**Comment by ugommirikwe** [comment]
@sgrekov Lovely. Thanks. I'm waiting for the invitation to the Slack Channel to come through. 

But, to be sure, do you have any documentation on how to use Inkremental in a Fragment? Whether in the `Fragment#onCreateView()` override or in any other way? Much appreciate your efforts on this project.

**Comment by sgrekov** [comment]
We didn't had examples for this, even though we have some utilities for fragments.
I made a PR with example 
https://github.com/inkremental/inkremental/pull/69/files
Hope you will find it useful!

**Comment by ugommirikwe** [comment]
> We didn't had examples for this, even though we have some utilities for fragments.
> I made a PR with example
> https://github.com/inkremental/inkremental/pull/69/files
> Hope you will find it useful!

Very useful indeed! Quite simple API :-) I think I'll step in and help with documenting this project, if you don't mind?

Because Google now recommends Single-Activity-Multiple-Fragments structure in Android apps, this issue I raised will be very helpful to lots of users out there who might want to use this library.

Next step for me now is to understand how to apply themes to Inkremental views.

More power to your elbows, @sgrekov 👍

**Comment by sgrekov** [comment]
> I think I'll step in and help with documenting this project, if you don't mind?

That would be very nice from your side!)

**Comment by r4zzz4k** [comment]
Yeah, our docs do need some love, any help is welcome. The only thing we should need before accepting any contributions as per #36 is to make sure we drop down license notices correctly -- we assume the code is covered by Apache 2.0 and docs under the same or something similarly permissive, but this should be fixed down for everyone to be safe.

I'd also like to have static site with docs, we'll probably investigate Github Pages for that as @Mishkun was in favor of that IIRC.

Feel free to work on docs locally, we'll try our best to be prepared to accept contributions in reasonable time.
