### ISSUE TITLE
AndroidX support widgets

### ISSUE THREAD

**Issue by sgrekov** [Inkremental/anvil#83]
Background - LayoutInflater for AndroidX support library do this smart substitution of platform widgets to the widgets from the AndroidX(support) libraries. That way developers don't need to handle it manually. 
Users of Inkremental can expect the same behavior, but it is not the same at the moment. Current, we can call either support widgets or platform widgets, and to call support widget we have to do it explicitly, like 
`appCompatButton {...`

I think we can mimic this behavior by providing additional artifacts to accompany existing "pure" platform artifacts, like 
`dev.inkremental:anvil-sdk:21-0.12`
`dev.inkremental:anvil-sdk-support:21-0.12`

And inside of those artifacts we can do instead of this
`fun button(configure: ButtonScope.() -> Unit = {}) = v<Button>(configure.bind(ButtonScope))` 
replace it with this 
`fun button(configure: AppCompatButtonScope.() -> Unit = {}) =v<AppCompatButton>(configure.bind(AppCompatButtonScope))`

@r4zzz4k @Mishkun  What are your thoughts on this?

**Comment by r4zzz4k** [comment]
@sgrekov Sounds reasonable. Is there a mapping somewhere which can be parsed automatically, or we'll have to support it manually?

**Comment by Mishkun** [comment]
@sgrekov Looks good for me, we need to update README to include these sources by default, though

**Comment by sgrekov** [comment]
>  Is there a mapping somewhere which can be parsed automatically, or we'll have to support it manually?

No, I don't think so( But there are not so many widgets, like 15-20, I think it would not a big problem to create and support such simple mapping.

**Comment by sgrekov** [comment]
> we need to update README to include these sources by default, though

Good point, thanks!

**Comment by r4zzz4k** [comment]
Sure, manual is OK.

So you suggest `-support` artifacts which can be added *instead* of usual ones, is that correct? Not sure I'm fond of this, but I'm also not sure if we can avoid this by overriding components...

**Comment by sgrekov** [comment]
Yes, in the apps, developers will need to choose which artifact they will need, **with** support, or **without**, but not together.
