### ISSUE TITLE
Absent AndroidX libraries

### ISSUE THREAD

**Issue by r4zzz4k** [Inkremental/anvil#86]
Looking through the list of AndroidX modules, I see some which we don't cover. Most of them contain one or two widgets, but still.
* [ ] [`androidx.camera`](https://developer.android.com/jetpack/androidx/releases/camera): [CameraView and PreviewView](https://developer.android.com/reference/androidx/camera/view/package-summary)
* [ ] [`androidx.emoji`](https://developer.android.com/jetpack/androidx/releases/emoji): [Lots of emoji-related views](https://developer.android.com/reference/androidx/emoji/widget/package-summary)
* [ ] [`androidx.webkit`](https://developer.android.com/jetpack/androidx/releases/webkit): some `WebView`-related extensions which can probably be added as attributes (if there are any -- should look into it a bit more).

These are covered by our support-v4 module, but we should probably redo it the same way AndroidX has: split into separate modules and add an umbrella legacy one:
* [ ] [`androidx.drawerlayout`](https://developer.android.com/jetpack/androidx/releases/drawerlayout): well, [DrawerLayout](https://developer.android.com/reference/kotlin/androidx/drawerlayout/widget/DrawerLayout)
* [ ] [`androidx.coordinatorlayout`](https://developer.android.com/jetpack/androidx/releases/coordinatorlayout): [CoordinatorLayout](https://developer.android.com/reference/kotlin/androidx/coordinatorlayout/widget/CoordinatorLayout)
* [ ] [`androidx.slidingpanelayout`](https://developer.android.com/jetpack/androidx/releases/slidingpanelayout): [SlidingPaneLayout](https://developer.android.com/reference/kotlin/androidx/slidingpanelayout/widget/SlidingPaneLayout)
* [ ] [`androidx.swiperefreshlayout`](https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout): [SwipeRefreshLayout](https://developer.android.com/reference/kotlin/androidx/swiperefreshlayout/widget/SwipeRefreshLayout)

That's not in any way a full list of stuff that's left (I've most probably missed something as this was just a glance) nor a list of things we have to have until 1.0. Let's just keep this here to address later.

**Comment by sgrekov** [comment]
We do have  DrawerLayout, CoordinatorLayout, SlidingPaneLayout, SwipeRefreshLayout in support-v4 module. Maybe it's worth splitting this module into standalone modules following the Androidx packaging strategy.

**Comment by r4zzz4k** [comment]
Oh, my bad, you're right. Yeah, we should remove the legacy v4 package, but that's a different story. I'll update the first post, thanks for correcting me!
